adapter:
  adapter_type: "discord"
  bot_token: "MTM4Mjg5MTcwODUxMzEyODQ4NQ.GtEgv8.EHaWjyEtv3TFd4xsqEBxyn-kilw0PQViQm3AaE"
  application_id: "1382891708513128485"
  guild: "1289595876716707911"
  channel: "1289595876716707914"
  retry_delay: 5
  connection_check_interval: 300
  max_reconnect_attempts: 5
  max_message_length: 1999
  max_history_limit: 100
  max_pagination_iterations: 10

attachments:
  storage_dir: "attachments/discord_adapter"
  max_age_days: 30
  max_total_attachments: 1000
  cleanup_interval_hours: 24
  max_file_size_mb: 8
  max_attachments_per_message: 10

caching:
  max_messages_per_conversation: 100
  max_total_messages: 1000
  max_age_hours: 24
  cache_maintenance_interval: 3600
  cache_fetched_history: true

logging:
  logging_level: "INFO"
  log_file_path: "logs/discord_adapter.log"
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_log_size: 5242880
  backup_count: 3

rate_limit:
  global_rpm: 30
  per_conversation_rpm: 30
  message_rpm: 15

socketio:
  host: "127.0.0.1"
  port: 8082
  cors_allowed_origins: "*"
